# Generated by Django 6.1.1 on 2026-09-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
