# Generated by Django 6.1.1 on 2026-09-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profile_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='logo',
        ),
    ]
